[repository]
name = "kitconcept-keywordmanager"
changelog = "CHANGELOG.md"
version = "version.txt"
version_format = "semver"
container_images_prefix = "ghcr.io/kitconcept/kitconcept-keywordmanager-"
compose = ["docker-compose.yml"]

[repository.towncrier]
section = "Project"
settings = "towncrier.toml"

[backend.package]
name = "kitconcept.keywordmanager"
path = "backend"
code_path = "src/kitconcept/keywordmanager"
changelog = "backend/CHANGELOG.md"
towncrier_settings = "backend/pyproject.toml"
base_package = "Products.CMFPlone"
publish = true

[frontend.package]
name = "@kitconcept/volto-keywordmanager"
path = "frontend/packages/volto-keywordmanager"
code_path = "src"
changelog = "frontend/packages/volto-keywordmanager/CHANGELOG.md"
towncrier_settings = "frontend/packages/volto-keywordmanager/towncrier.toml"
base_package = "@plone/volto"
publish = true

[cookieplone]
template = "monorepo_addon"
template_version = "cda10db886223a9aa9be1b1368484296418bb880"
generated_date = "2026-05-29 09:47:12"
