[repository]
name = "kitconcept.keywordmanager"
changelog = "CHANGELOG.md"
version = "version.txt"
version_format = "semver"
container_images_prefix = "ghcr.io/kitconcept/kitconcept.keywordmanager"
compose = ["docker-compose.yml"]

[repository.towncrier]
section = "Project"
settings = "towncrier.toml"

[backend.package]
name = "kitconcept.keywordmanager"
path = "backend"
changelog = "backend/CHANGELOG.md"
towncrier_settings = "backend/pyproject.toml"
base_package = "Products.CMFPlone"
publish = true

[frontend.package]
name = "volto-keywordmanager"
path = "frontend/packages/volto-keywordmanager"
changelog = "frontend/packages/volto-keywordmanager/CHANGELOG.md"
towncrier_settings = "frontend/packages/volto-keywordmanager/towncrier.toml"
base_package = "@plone/volto"
publish = true

[cookieplone]
template = "monorepo_addon"
template_version = "ca9ba9fa67bc9a824eab13962a63db230c93679e"
generated_date = "2026-03-19 15:50:09"
